### ISSUE TITLE
[state]Map not supported?

### ISSUE THREAD

**Issue by mmmintdesign** [lit-apps/lit-app#8]
I can't tell if there is something in addition needed to use Map, but it doesn't seem to react if you use Map?

**Comment by christophe-g** [comment]
I am not user I fully understand your question,  but if you mean the state does not react when a property of type `Map` is updated, this would be relevant: https://lit.dev/docs/components/properties/#mutating-properties , as State properties share the same reactive behaviors as lit properties.

**Comment by mmmintdesign** [comment]
> I am not user I fully understand your question, but if you mean the state does not react when a property of type `Map` is updated, this would be relevant: https://lit.dev/docs/components/properties/#mutating-properties , as State properties share the same reactive behaviors as lit properties.
